language: python
python:
  - "2.7"

env:
  - DJANGO_VERSION=1.4.10
  - DJANGO_VERSION=1.5.5
  - DJANGO_VERSION=1.6

install:
  - pip install -r ereports/requirements/install.pip
  - pip install -r ereports/requirements/testing.pip

script: py.test -vv
